<!--
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
    $productTypeInstance = $product->getTypeInstance();
   if ($product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
    $usedProducts = $productTypeInstance->getUsedProducts($product);

    ?>
<?php
        foreach ($usedProducts  as $child) {?>
            <span class="myli" id="div<?php echo $child->getId()?>"  style="display:none">
            <?php
            $productStockObj = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($child->getId());
            echo "Disponibles para entrega hoy: ".round($productStockObj->getData('qty'));
            ?>
            </span>

 <?php    }   ?>

  <?php }else{
     $productStockObj = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($product->getId());
     echo "Disponibles para entrega hoy: ".round($productStockObj->getData('qty'));
	    }?>
-->
<?php
    $values = $block->saleble();
    foreach ($values as $k => $b) {?>
    <span class="myli" id="div<?php echo $k?>"  style="display:none">
        <?php
            foreach ($b as $q) {
                ?> <p style="margin: 0 "><?php echo $q;?></p>
            <?php
            }
            ?>
    </span>
    <?php
    }?>

<!--
<?= "<span>".__("Result: ", $block->saleble()) . "</span>";?>
-->
